app_tracoll/urls.py
from django.urls import path
from . import views

urlpatterns = [path('' , views.index , name='index' ),
               path('authors/', views.AuthorListView.as_view(), name='authors'),
               path('translations/' , views.TranslationListView.as_view() , name='translations' ),
               path('translation/<int:pk>', views.TranslationDetailView.as_view(), name='translation-detail'),
               path('translation/<int:pk>/edit/',views.translating_page,name='translating-page'),
               path('author/<int:pk>', views.AuthorDetailView.as_view(), name='author-detail'),
               ]
               





pj_tracoll/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

# URL matching from PROJECT LEVEL TO APPLICATION LEVEL
from django.urls import include
urlpatterns += [path('app_tracoll/', include('app_tracoll.urls')),]

# URL MAPPING USED TO redirect to app_tracoll when receive empty URL
from django.views.generic import RedirectView
urlpatterns += [ path('', RedirectView.as_view(url='app_tracoll/')),]

# Redirect to home URL after login
LOGIN_REDIRECT_URL = '/'

# Redirect Django-generated emails to console
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# adds 8 urls automatically generated by Django to handle login / logout, etc
urlpatterns += [ path('accounts/', include('django.contrib.auth.urls')), ]


app_tracoll/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User


class Author(models.Model):

    AUTHOR_TYPOLOGY=(('P', 'Poet'),('S','Songwriter'),('B','Band'),)
    type_of_author = models.CharField(max_length = 1,choices = AUTHOR_TYPOLOGY,
                              blank = False, help_text = 'Typology of author')
    name_of_author = models.CharField(max_length = 100, blank = False) 

    class Meta:
        ordering = ['name_of_author']
        permissions = (("can_watch_every_status", "You can watch every text status"),)
    
    # used for visualization in admin page
    def __str__(self):
        return f'{self.name_of_author}' 

    # used in Author List to get URL to specific author
    def get_absolute_url(self):
        return reverse('author-detail', args=[str(self.id)])


class Language(models.Model):

    name_of_language = models.CharField(max_length= 100, blank= False)

    class Meta:
        ordering = ['name_of_language']
   
    # used for visualization in admin page
    def __str__(self):
        return f'{self.name_of_language}'


class Text(models.Model):

    TEXT_TYPOLOGY = (('P', 'Poem'),('S', 'Song'),)
    type_of_text= models.CharField(max_length = 1,choices = TEXT_TYPOLOGY,
                                   blank = False,help_text = 'Type of text')
    
    # title and content CANNOT be blank
    title = models.CharField(max_length= 100, blank= False)
    content = models.TextField(max_length= 2000, blank= False)

    original_language = models.ForeignKey(Language, null= True,  on_delete = models.SET_NULL)

    # null = True --> author can be unknown
    author= models.ForeignKey(Author, null = True, on_delete= models.SET_NULL)

    # tuple with choices for translation state
    TRANSLATION_STATE=(('W','Waiting for translation'),
                       ('L','Under revision by administrator'),
                       ('E','Existing translation and editable by authenticated users'),
                       ('V','Final translation NOT editable anymore'),)
    
    status_of_translation = models.CharField(max_length = 1,choices = TRANSLATION_STATE,
                              blank = False, default = 'W',
                              help_text = 'State of traslation')

    class Meta:
        ordering = ['title']
   
    # used for visualization in admin page
    def __str__(self):
        return f'{self.title}'


class Translation(models.Model):
    
    translated_title = models.CharField(max_length=100)   
    translated_content = models.TextField(max_length=2000)
    original_text =models.OneToOneField(Text, null= True,  on_delete = models.SET_NULL)

    creator =models.ForeignKey(User,on_delete = models.SET_NULL,
                                 null = True,blank = True)

    class Meta:
        ordering = ['translated_title']
        permissions = (("permession_of_edit_text_with_every_status", "You can edit every text in every status")
                       ,("edit_W_and_E_status_texts","You can edit W and E text status"))

    # used for visualization in admin page
    def __str__(self):
        return f'{self.translated_title}'

    # used in Translation List to get URL to specific translation
    def get_absolute_url(self):
        return reverse('translation-detail', args=[str(self.id)])





app_tracoll/forms.py
import datetime
from django import forms
from django.core.exceptions import ValidationError


# form used to insert data about translation by athenticated users
class TranslatedTextForm(forms.Form):
	# form fields
	new_translated_title = forms.CharField(max_length=100)
	new_translated_content = forms.CharField(widget=forms.Textarea, max_length=2000)
	
	# validation methods, one for each form field. no check is applied here as
	# max_lenght and blank constraints are automatically checked in each field

	def clean_new_translated_title(self):
		data = self.cleaned_data['new_translated_title']
		return data

	def clean_new_translated_content(self):
		data = self.cleaned_data['new_translated_content']
		return data

app_tracoll/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from app_tracoll.forms import TranslatedTextForm

from .models import Language, Text, Author , Translation

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import PermissionDenied

#function based view of home page 
def index(request):

    # objects -> utility provided by Django for several 
    # actions like counting occurences in a database table
    n_texts = Text.objects.all().count()
    n_translations = Translation.objects.all().count()
    n_authors = Author.objects.all().count()
    num_languages = Language.objects.all().count()

    # cookies management
    num_visits = request.session.get('num_visits', 0)
    num_visits = num_visits + 1
    request.session['num_visits'] = num_visits
    request.session.modified = True
    
    # context for index.html template rendering 
    ctx = {
        'num_texts' : n_texts,
        'num_translations' : n_translations,
        'num_authors' : n_authors,
        'num_visits': num_visits,
        'num_languages': num_languages,
    }
    return render(request, 'index.html',context=ctx)

#------------------------------------------------------------------------------------
# views for visualization of a list of authors or translations

class AuthorListView(generic.ListView):
    # pagination parameter
    paginate_by = 8
    # model where to retrieve a list of records
    model = Author

class TranslationListView(generic.ListView):
    # pagination parameter
    paginate_by = 6
    # model where to retrieve a list of records
    model = Translation

    # override of this function
    def get_queryset(self):
        # lookup across relation of Text (calling original_text, name of linked field in 
        # Translation table) and Translation
        # this function will be called and the result will be saved in translation_list object
        # that can be used in template translation_list.html
        final_translations = Translation.objects.filter(original_text__status_of_translation = 'V')
        return final_translations.order_by('translated_title')
 
   
#------------------------------------------------------------------------------------
# views to retrieve details of a single author or translation

class TranslationDetailView(generic.DetailView):
    # model where single instance is retrieved
    model = Translation


class AuthorDetailView(generic.DetailView):
    # model where single instance is retrieved
    model = Author

    # override of this method
    def get_context_data(self, **kwargs):
        # call super class method to mantain same funcionalitites
        ctx = super().get_context_data(**kwargs)

        # add number of final texts of this author to context ONLY when user is NOT logged in
        if(not self.request.user.is_authenticated 
           and not ("can_watch_every_status" in self.request.user.get_all_permissions())
        ):
            #find number of final texts of the given author. ONLY when user is NOT logged in
            number_of_final_texts = Text.objects.filter(author_id=self.get_object().pk).filter(status_of_translation__exact = 'V').count()
            ctx['number_of_final_texts'] = number_of_final_texts

        return ctx
        

@login_required
def translating_page(request, pk):

    # check permission (for Normal user and Administrator)

    if (request.user.has_perm('app_tracoll.permession_of_edit_text_with_every_status')
        or request.user.has_perm('app_tracoll.edit_W_and_E_status_texts')):
        
        text= get_object_or_404(Text, pk=pk)

        #first interaction with form 
        if (request.method != 'POST'):
            
            if(text.status_of_translation == 'W'  or 
               (text.status_of_translation == 'L' and not(request.user.has_perm('app_tracoll.permession_of_edit_text_with_every_status')))):
                previous_data = {
                    # used for texts wating for translation-> return default empty form in this case
                    # or
                    # text under revision by administrator ('L') when user 
                    # has NO editing permission for 'L' texts -> avoid passing translation data
                                'new_translated_title': "",
                                'new_translated_content':  ""
                                }
            else:
                # there are some data already inseted in database and user has permissions-> show data in the form
                    previous_data = {
                            'new_translated_title': text.translation.translated_title,
                            'new_translated_content':  text.translation.translated_content
                            }

            # create form with previous_data
            form = TranslatedTextForm(initial=previous_data)
            # define a context used in page rendering
            ctx = { 'form': form, 'text': text}
            return render(request, "app_tracoll/translating_page.html", ctx)
        else:
            # further interactions with forms
            
            form = TranslatedTextForm(request.POST)
            
            # is_valid() will call every clean method to validate form fields
            if form.is_valid():

                # if text doesn't have a translation, add ONE 
                # as in this branch i'm sure translated 
                # title and translated content (passed with form)
                #  are NOT empty -> thanks to is_valid() 
                if(text.status_of_translation == 'W'):

                    #create new translation object
                    translation_obj = Translation()

                    #link text to translation_obj
                    text.translation = translation_obj
                    text.status_of_translation = 'E'
                    text.save()

                    #link translation_obj to text
                    translation_obj.original_text = text

                    # initialize field of translation_obj
                    translation_obj.creator = request.user
                    translation_obj.translated_title = form.cleaned_data['new_translated_title']
                    translation_obj.translated_content = form.cleaned_data['new_translated_content']

                    # save translation
                    translation_obj.save()

                    # link translation to user
                    request.user.translation_set.add(translation_obj)
                    request.user.save()

                else:
                    # translation is already present -> show title and text of translation in the form
                    text.translation.translated_title = form.cleaned_data['new_translated_title']
                    text.translation.translated_content = form.cleaned_data['new_translated_content']
                    text.translation.save()
                
                # after correct data insertion in form, user will be
                # redirected to author's detail page
                return HttpResponseRedirect(reverse("author-detail", args=[text.author.pk]))

            else:
                # had some form validation error, return form 
                ctx = { 'form': form, 'text': text }
                # redirect to form page, Django's automatic facilities
                # will attach error messages to interested fields
                return render(request, 'app_tracoll/translating_page.html', ctx)
    else:
        # will automatically redirect to 403.html page
        raise PermissionDenied()


app_tracoll/templates/app_tracoll/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
	<div class="author_detail_div">
		
		<h2 class="author_detail_title"> {{ author.name_of_author }} </h2>
		
		{% if author.type_of_author == 'P' %}<p>POET</p>
		{% elif author.type_of_author == 'B' %}<p>BAND</p>
		{% elif author.type_of_author == 'S' %}<p>SONGWRITER</p>
		{% endif %}

		<br>

		{% if user.is_authenticated %}			<!-- ------------------------ for authenticated user ------------------------------------- -->
			<h4>All texts: </h4>

			{% if author.text_set.all %}
				<ul>
					{% for text in author.text_set.all %}
					
					
						{% if text.status_of_translation == 'V' %}							<!-- 'V' status -->
						<li class="detail_list_links">
							<a href="{{text.translation.get_absolute_url}}" target="_self">{{text.title}}</a>
							<span>
							<!--how to display flags; if you want to add flag image, add it to 'flags' directory with name of the language -->
							<img class="fg_min" src="../../static/flags/{{text.original_language.name_of_language}}.svg">
							</span>
							:&nbsp &nbsp 
							<b><span class="green-text">FINAL TRANSLATION <img id="pen" src="../../static/flags/Italian.svg"></span></b>
						</li>
						{% else %}
							{% if perms.app_tracoll.can_watch_every_status %}
							<li class="detail_list_links">
								<a href="{% url 'translating-page' text.pk %}" target="_self">{{text.title}}</a>
								<span>
								<!--how to display flags; if you want to add flag image, add it to 'flags' directory with name of the language -->
								<img class="fg_min" src="../../static/flags/{{text.original_language.name_of_language}}.svg">
								</span> 
								:&nbsp &nbsp
								

								{% if text.status_of_translation == 'W' %}					<!-- 'W' status -->
								<span class="red-text">WAITING FOR TRANSLATION</span></b>
									
								{% elif text.status_of_translation == 'E' %}				<!-- 'E' status -->
								<span class="orange-text">
								<img id="pen" src="../../static/images/pen.png">			<!-- pen image for editable transion -->
								EDITABLE TRANSLATION
								</span>
									
								{% elif text.status_of_translation == 'L' %}				<!-- 'L' status -->
								<span class="gray-text">UNDER REVISION BY ADMINISTRATOR</span>

								{% endif %}
							</li>
							{% endif %}
						{% endif %}

								
							
					{% endfor %}
				</ul>
			{% else %}
					<h4 class="text-danger">This author has no Texts</h4>
			{% endif %}

		{% else %}								<!-- ------------------------ for not authenticated user --------------------------------------->
			{% if author.text_set.all %}
				{% if number_of_final_texts == 0 %}
					<h4 class="text-danger">This author has no Texts with final translatons</h4>
				{% else %}
					<h4>All translated texts: </h4>
					<ul>
						{% for text in author.text_set.all %}
							{% if  text.status_of_translation == 'V' %}
							<li class="detail_links">
								<a href="{{text.translation.get_absolute_url}}" target="_self">{{text.title}}</a>
								&nbsp
								<span>
								<!--how to display flags; if you want to add flag image, add it to 'flags' directory with name of the language -->
								<img class="fg_min" src="../../static/flags/{{text.original_language.name_of_language}}.svg">
								</span> 
							</li>
							{% endif %}
						{% endfor %}
					</ul>
				{% endif %}
			{% else %}
				<h4 class="text-danger">This author has no Texts</h4>
			{% endif %}
		{% endif %}
	</div>
{% endblock %}


app_tracoll/templates/app_tracoll/author_list.html
{% extends "base_generic.html" %}
	{% block content %}
	<h1 class="author_list_title">Authors List</h1>	
	<br>												
		<div class="author_list_div">
			{% if author_list %}
				{% for author in author_list %}         <!-- displaying author -->
				<ul>
					<li class="detail_list_links">
						<a href="{{ author.get_absolute_url }}">{{ author.name_of_author }}</a>
					</li>
				</ul>
				{% endfor %}
			{% else %}
				<p>There are no authors in the app.</p>
			{% endif %}
		</div>
	{% endblock %}>

app_tracoll/templates/app_tracoll/translating_page.html
{% extends "base_generic.html" %}

{% block content %}
	<div class="translating_page_div">
		<h3 class="translating_page_title">Translation Page: </h3>

		<p><b>Title:</b> {{text.title}}</p>								<!-- ORIGINAL TEXT -->
		<p><b>Content:</b>  {{text.content}}</p>						<!-- ORIGINAL CONTENT -->
		<hr>
		{% if user.is_authenticated %}													<!-- IF AUTHENTICATED -->
			{% if perms.app_tracoll.permession_of_edit_text_with_every_status %}		<!-- ADMIN -->
				<form action="" method="post">
					{% csrf_token %}
					<table style="text-align:left;width:80%;">
						{{ form.as_table }}
					</table>
					<input type="submit" value="Submit">
				</form>
			{% elif perms.app_tracoll.edit_W_and_E_status_texts and text.status_of_translation != 'L'%}	<!-- AUTHENTICATED USER (can't edit text under control of admin)-->
				<form action="" method="post">
					{% csrf_token %}
					<table style="text-align:left;width:80%;">
						{{ form.as_table }}
					</table>
					<input  type="submit" value="Submit">
				</form>
			{% else %}
				<p class="text-danger">You DO NOT have permission to edit or add translation  <br>because this text is under review by administrator </p>
			{% endif %}
		{% else %}
			<p class="text-danger">You DO NOT have permission to edit or add translation  <br>because you are NOT authenticated</p>
		{% endif %}
	</div>
{% endblock %}

app_tracoll/templates/app_tracoll/translation_detail.html
{% extends "base_generic.html" %}

{% block content %}

    <div class="translation_detail_div">

        {% if translation.original_text.status_of_translation == 'V' %}     <!--FURTHER checking text in final translation status -->

            <h2 class="translation_detail_title">Original: </h2>            <!-- **ORIGINAL PART** -->
            <div id="td_div1"> 
                <h3 class="translation_detail_subtitle">  

                    <!--how to display flags; if you want to add flag image, add it to 'flags' directory with name of the language -->
                    <span><img class="flag" src="../../static/flags/{{translation.original_text.original_language.name_of_language}}.svg"></span>
                
                    &nbsp &nbsp &nbsp &nbsp                                 <!-- space between flag and title -->
                    {{ translation.original_text.title }}                   <!-- ORIGINAL TITLE -->
                </h3>
                <p>{{ translation.original_text.content }}</p>              <!-- ORIGINAL CONTENT -->
            </div>
            <br>                                                            <!-- ---------------------------------------------------------- -->
            <hr>
            <h2 class="translation_detail_title">Translated: </h2>          <!-- **TRANSLATED PART** -->
            
            <div id="td_div2">
                <h3 class="translation_detail_subtitle">
                <span><img class="flag" src="../../static/flags/Italian.svg"></span>        <!-- Italian flag because traslation is always in italian language --> 
                &nbsp &nbsp &nbsp &nbsp                                                     <!-- space between flag and title -->
                {{ translation.translated_title }}                                          <!-- TRANSLATED TITLE -->
                </h3>                 
                <p>{{ translation.translated_content }}</p>                                 <!-- TRANSLATED CONTENT -->
            </div>

        {% else %}

            <p>This is NOT a Final Translation, and CANNOT be displayed in this page. 
            <br><a href=" {% url 'index' %}" target="_self">BACK HOME</a></p>

        {% endif %}
    </div>

{% endblock %}

app_tracoll/templates/app_tracoll/translation_list.html
{% extends "base_generic.html" %}

{% block content %}
	<h1 class="translation_list_title"> Final translations List</h1>
	<br>
	<div class="translation_list_div">
		<table style="width:60%">
			{% for translation in translation_list %}
			<tr>
				<!-- 1° column  -->
				<td class="detail_list_links">
					<ul>
						<li>
							{% if translation.original_text.status_of_translation == 'V' %}					<!-- final status translation -->
						
							<b><a href="{{translation.get_absolute_url}}" target="_self">
							{{ translation.translated_title }}</a></b>										<!-- title of translation -->

							<!-- flags diplaying: -->
							&nbsp
							<span>
							<!--how to display flags; if you want to add flag image, add it to 'flags' directory with name of the language -->
							<img class="fg_min" src="../../static/flags/{{translation.original_text.original_language.name_of_language}}.svg">
							</span>
							/
							<img class="fg_min" src="../../static/flags/Italian.svg">
							<!-- -------------------- -->
						</li>
					</ul>
				</td>
				<!-- 2° column  -->
				<td>
					<a href="{{translation.original_text.author.get_absolute_url}}" target="_self">
						{{ translation.original_text.author.name_of_author }}								<!-- author name  -->
					</a>
					{% endif %}
				</td>
			</tr>
			{% empty %}
				<p>There are no translations in the app.</p>
			{% endfor %}
		</table>
	</div>

{% endblock %}>